### PR TITLE
Several updates to skill handling and pre-responses

### PR DESCRIPTION
**Pull request by SawPsyder**
**Draft**
Still a draft as long as this TODO stand: Implement auto generated pre-responses toggle in config / client.

**Description**
Updating several small things in the code.
Breaking change for skills in development is the renaming of `gpt_call` to `llm_call`.

Adding an option to add a small "pre-response" for a user request with a tool call behind it to keep the conversation natural.
This is configurable for skills with `is_waiting_response_needed` (thats the pre-response, defaulting to `False`) and `is_summarize_needed` (Thats the normal message, defaulting to `True`) on a skill level. The tool name is a parameter to enable per-tool configuration in a function.
Also noteworthy: If the AI does not provide a tool message content in when requesting tool calls and therefore a auto generated one is used, the `is_summarize_needed` flag is automatically set to `True`, no matter the configuration.
Also `execute_command` is configured with `is_waiting_response_needed`=`True` and `is_summarize_needed` = False.

Would be great to get the AI to reliably provide a message content on tool calls. But not sure this is possible.

**Changelog**
- moving threaded execution from skill level to wingman level
- renaming `gpt_call` method on skill level to `llm_call`
- add new hook for skills: `on_add_assistant_message` (similar to `on_add_user_message`)
- add pre-response option
- add pre-response generation | TODO: implement in config & client
- add "interrupt" flag return value for `_get_response_for_transcript` (depends if a pre-response was given)
- updating quick commands skill to utilize new hook and new instant command options (one phrase with multiple commands)
- updating uexcorp and websearch skill to enable `is_waiting_response_needed` as first test cases.

### CODE REVIEW

**Comment by Shackless** [comment]
Do we really need a user config flag for this? I think this might be something skills could just define to do as it's really hard for users to understand what's going on here. If yes: Where? Is this a global settings overriding whatever the skills define or a "per Wingman" flag?

**Comment by SawPsyder** [comment]
I thought there would be a flag/setting to enable the auto generated static pre-responses.
I'm not sure everybody wants them, as they are a bit generic and might not always fit the current context a conversation is in.

So it will overwrite no setting, it will just prevent generic auto generated pre-responses if no initial pre-response was provided by the llm.

**Comment by Shackless** [comment]
Okay. You can add this to the Core config interface where you want it to be and implement it. I can then add it to the client.

**Comment by SawPsyder** [comment]
For example I expect this message history:
- User: give me a good trading route
- LLM: I will calculate the routes.. + tool calls
- LLM: Here is the best...

But mostly the LLM does not provide a initial message:
- User: give me a good trading route
- LLM: tool calls
- LLM: Here is the best...

Thats were the auto generated one come into play:
- User: give me a good trading route
- LLM: One moment.. + tool calls
- LLM: Here is the best...

**Comment by Shackless** [comment]
Yeah I got that. So if you disabled this new flag, we'd just skip the pre-response completely? Not sure this is a setting that users will understand but I don't really mind adding it either. @TimoKorinth your take on this?

**Comment by SawPsyder** [comment]
This is meant for "usual" llm conversations with tool calls and not for a completely integrated gpt-4 omni model (voice & text).
So its alright it wont effect the behavior of that.

**Comment by teddybear082** [comment]
For the changes to threaded execution can a skill creator just call the threaded execution command directly still or will they have to import it from a wingman? I like that you had this as an API of sorts with skills to make it easier to create them.

Aside from that when does the phrase creation run? Is that just a function that can be called from the UI someday?  It occurs to me right now all the phrases are created but they are being sent for voice creation at runtime right? That would explain why there is still a second or two delay before they play?

**Comment by Shackless** [comment]
needs to be rebased and implemented after #178 is merged

**Comment by SawPsyder** [comment]
@teddybear082
The threaded execution method is still callable from a skill as before.
Thats because on skill init `skill.threaded_execution` is mapped to `wingman.threaded_execution`. (Same as with the llm_call function)
So just `self.threaded_execution(async_function, argument1, argument2, argument3, ...)`

And regarding the phrases: They are generated on `wingman.prepare`. This is called after validation. And it runs in its own thread so you don't notice it.
And yes, they are only generated as text and have to be converted to audio on playback, hence there is still a delay.
Also they are not always played out, but only if the AI, in its initial answer, has tool calls. So there is always the wait for the first AI answer to decide if they are played back or not.

**Comment by SawPsyder** [comment]
Added config option `features.use_generic_instant_responses` and adapted vision skill.

Client update for config still open I guess?

**Comment by SawPsyder** [comment]
I removed the draft marker. So feel free to merge this, whenever ready.

**Comment by teddybear082** [comment]
Thanks! Good to know the skills API would be intact.  Thinking ahead a bit, if we got to the point where the phrases were then cached into audio files in the wingman’s config files after generation using the voice of the wingman that has been selected at the time, would another rewrite be necessary to play those for every response or do you think that would fit into this framework?  Obviously it’s up to Simon and Timo what is the ultimate vision.  I can see trade offs with each.  With caching audio it’s the best chance to get immediate feedback but in certain circumstances there might be an unnatural pause after, like with a very short waiting sound and a very long action, so I could see pro’s and con’s of each.

**Comment by SawPsyder** [comment]
We talked about this in discord. There needs to be a real audio player service and the option to generate audio without playing it.
This will allow a later, better version of these instant responses to convert the phrases into audio files proactively and play them immediately, removing the delay of tts on runtime.

The endpoints on the skill level will most likely remain the same. Just the process of preparing the phrases will be different.

**Comment by SawPsyder** [comment]
When it comes to that, I will provide a new public method in the wingman to redo the audio phrase caching. Thats shouldn't be a big thing.
The big thing is actually building/splitting the audio player and audio tts service.

**Comment by Shackless** [comment]
Okay, let’s see how this plays out in testing. I’ll add the UI flag tomorrow and include it in the next pretest version.

**Pull request merged**
