### PR TITLE
add skill quick_commands

### PR DESCRIPTION
**Pull request by SawPsyder**
Adding a new skill to the lineup: "Instant activation learning".
Something I had running as a custom wingman in earlier version and really liked in combination with voice activation. Now converted to a skill.

This skill checks the message history after each user request to see if a user request resulted in one command execution.
If this is the case, its added to a learning list. And as soon, as the configurable limit is hit, the phrase gets injected into current instant activation phrases for this command.

This drastically speeds up regular requests, like "Turn on the quantum drive", over time without manual configuration work.

Info:
Currently this system hangs one message behind. Meaning it checks the previous user message and its result on a new user message event, instead of checking after the system answered.
This is due to a missing hook and will be fixed in a future release, when more hooks are available.

Changelog:
- added skill "Instant activation learning"

### CODE REVIEW

**Review by Shackless — COMMENTED** [review]
Can we make the name and description/hint a bit more user/UI-friendly? Imagine you didn't know that this was doing and saw it in a list among other skills like Spotify.

**Comment by SawPsyder** [comment]
I do think the title/name is very accurate and good. It is called instant activation phrases in Wingman AI and this learns them.
When it comes to the description: Maybe "Automatically learns instant activation phrases for your wingman commands."

What do you reckon? Any suggestions?

**Comment by Shackless** [comment]
Suggestion:

Name: Quick Commands
Desc: "Automatically learns instant activation phrases for commands you use regularly, speeding up their execution time."

**Comment by SawPsyder** [comment]
Sounds good. Will do that later

**Pull request merged**
