### PR TITLE
implement mouse buttons, scroll, typewrite, multiple modifier keys, moveto and move (relative) inputs

### PR DESCRIPTION
**Pull request by teddybear082**
-add commands that should work for either directinput or pyautogui

-tested on windows, needs testing on mac

-if user enters primary, middle or secondary as the key for a command, will use left, middle, right mouse button clicks

-also supports hold commands with mouse clicks

### CODE REVIEW

**Comment by Shackless** [comment]
According to their docs, PyAutoGui (MacOS) only supports „left“, „right“ and „middle“ as mouse button names. Pydirectinput adds „primary“ and „secondary“ as alias but we should stick to the common ground. Haven’t tested yet, can do after Christmas. Thank you!

**Comment by teddybear082** [comment]
Sounds good, have a great Christmas! Let me know how your testing on Mac goes when you get to it.  I realized with fresh eyes and a cup of coffee this morning that I could test with pyautogui by commenting out the statements that make the import of either pydirectinput or pyautogui conditional, and forcing pyautogui to import as key_module.  

In doing this test, at least on windows, current code works as expected on pyautogui.  

Pyautogui's underlying code also appears to set the primary and secondary aliases here: https://github.com/asweigart/pyautogui/blob/master/pyautogui/__init__.py in its enums and in its normalize_button commands convert primary and secondary to left and right (maybe depending on whether user has initiated left-handed mode, can't really tell).  

All that said, _even if_ this change does work on MacOS as-is, of course up to you guys from a user standpoint if its better to have a "-mouse" instead of "-key" event in the config. I haven't read enough of the code to figure out how to translate a new event like that from the config file down into the wingmen but my guess is it would be relatively easy for the ShipBit team. Maybe having a separate -mouse event would make sense if you would also look to add additional sub events besides hold and wait such as movetoabsolute: (x,y), movetorelative: (x,y), movetoicon: "icon/file/path" and selectwindow:"windowtitlestring".

**Comment by teddybear082** [comment]
Separately looks like someone has a PR that supports scrolling on pydirectinput but unfortunately hasn’t been implemented yet; https://github.com/learncodebygaming/pydirectinput/pull/22/files


Looks like _maybe_ it’s possible to pull a certain PR with pip install but I’ve never done it before; in theory this would prevent having to use fallbacks for scrolling: https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip

**Comment by teddybear082** [comment]
Example of new commands (not implemented in sample config since I don't know what ways you might have to actually use these inputs in star citizen)

mouse_commands_example

**Comment by teddybear082** [comment]
OK most recent commit has support for people to input a list of modifier keys if they want or just use the default single functionality.  So for instance: 
`modifier: altleft `

or 

`modifier: altleft, shift, ctrlright`

or 

`modifier altleft,shift,ctrlright `

will all work work.

**Comment by Shackless** [comment]
Cool, thanks! Would you mind adding some demo command to the example config that explains the new functionality for the 3% who are actually reading the config documentation? ;)

**Comment by teddybear082** [comment]
Sounds good thank you!

**Comment by teddybear082** [comment]
Ok I added some examples in sampleconfig.yaml.  Thanks!  Hope it works well on mac!

**Comment by bukit-kronik** [comment]
Thank you teddybear for contributing, typewrite, multiple modifier and mouse move will significantly increase wingman experience. A game changer in my book. Can't wait for the release.

**Comment by teddybear082** [comment]
> Thank you teddybear for contributing, typewrite, multiple modifier and mouse move will significantly increase wingman experience. A game changer in my book. Can't wait for the release.

Thanks! Hopefully it all works ok on Mac!

**Pull request merged**
